#ifndef MEMORIA_MEMORIA_INSERT_REQUEST_HANDLER_H_
#define MEMORIA_MEMORIA_INSERT_REQUEST_HANDLER_H_

int _manejar_insert(struct insert_request, void*);

#endif /* MEMORIA_MEMORIA_INSERT_REQUEST_HANDLER_H_ */
