#ifndef MEMORIA_MEMORIA_SELECT_REQUEST_HANDLER_H_
#define MEMORIA_MEMORIA_SELECT_REQUEST_HANDLER_H_

int _manejar_select(struct select_request, void*);

#endif /* MEMORIA_MEMORIA_SELECT_REQUEST_HANDLER_H_ */
